import type {SourceRecord} from '../domain/contracts'
import {asInstitutionId,asPublicationId,asSourceId} from '../domain/ids'

const rawSources=[
  {
    "id": "si-human-evidence",
    "type": "institutional-synthesis",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Evidence",
    "url": "https://humanorigins.si.edu/evidence",
    "role": "Evidence framework",
    "note": "Organizes human-evolution evidence across fossils, archaeology, genetics and dating.",
    "scope": "Human evolution evidence taxonomy"
  },
  {
    "id": "si-dating",
    "type": "institutional-synthesis",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Dating",
    "url": "https://humanorigins.si.edu/evidence/dating",
    "role": "Dating methods overview",
    "note": "Explains relative dating, radiometric methods and other chronological approaches used in human-evolution research.",
    "scope": "Dating methodology"
  },
  {
    "id": "si-3d",
    "type": "institutional-synthesis",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "3D Collection",
    "url": "https://humanorigins.si.edu/evidence/3d-collection",
    "role": "3D collection policy",
    "note": "Describes CT/laser scanning and the availability limits for fossil hominin 3D data.",
    "scope": "3D specimens and reuse policy"
  },
  {
    "id": "si-human-species-index",
    "type": "institutional-synthesis",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Human Fossils · Species",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species",
    "role": "Species index",
    "note": "Institutional species index used as a high-level reference for fossil taxa and time ranges.",
    "scope": "Human fossil species index"
  },
  {
    "id": "si-neanderthal-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Homo neanderthalensis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/homo-neanderthalensis",
    "role": "Species record",
    "note": "Institutional species overview and fossil context for Neanderthals.",
    "scope": "Homo neanderthalensis"
  },
  {
    "id": "si-neanderthal-dna",
    "type": "institutional-synthesis",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Ancient DNA and Neanderthals",
    "url": "https://humanorigins.si.edu/evidence/genetics/ancient-dna-and-neanderthals",
    "role": "Genetics synthesis",
    "note": "Summarizes ancient DNA evidence, Neanderthal–modern human gene flow and preservation constraints.",
    "scope": "Neanderthal genetics"
  },
  {
    "id": "si-feldhofer",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Feldhofer · Neanderthal 1",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/fossils/feldhofer",
    "role": "Specimen record",
    "note": "Institutional record for the classic Feldhofer specimen discovered in 1856.",
    "scope": "Neanderthal 1 / Feldhofer"
  },
  {
    "id": "si-d2282",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "D2282",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/fossils/d2282",
    "role": "Specimen record",
    "note": "Institutional record for the Dmanisi cranium D2282.",
    "scope": "Dmanisi / early Eurasian Homo"
  },
  {
    "id": "si-feldhofer-3d",
    "type": "museum-3d",
    "publisher": "Smithsonian 3D Digitization",
    "institution": "Smithsonian Institution",
    "title": "Homo neanderthalensis cranium · Feldhofer",
    "url": "https://3d.si.edu/object/3d/homo-neanderthalensis-cranium%3A5b3ead12-0fb2-4a9b-b5bf-b7a92be656e8",
    "role": "Museum 3D record",
    "note": "Official Smithsonian 3D record linked from the Feldhofer specimen layer; the app opens the institutional viewer rather than mirroring the mesh.",
    "scope": "Feldhofer / Neanderthal 1 3D viewer"
  },
  {
    "id": "si-sapiens-300ka",
    "type": "institutional-synthesis",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Our species arose at least 300,000 years ago",
    "url": "https://humanorigins.si.edu/research/whats-hot-human-origins/our-species-arose-least-300000-years-ago",
    "role": "Research summary",
    "note": "Summarizes the Jebel Irhoud evidence and its implications for the early Homo sapiens record.",
    "scope": "Jebel Irhoud / Homo sapiens"
  },
  {
    "id": "nature-hublin-2017",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens",
    "year": 2017,
    "authors": "Jean-Jacques Hublin et al.",
    "journal": "Nature 546, 289–292",
    "doi": "10.1038/nature22336",
    "url": "https://doi.org/10.1038/nature22336",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Reports the Jebel Irhoud fossil material and discusses its place within early Homo sapiens evolution.",
    "scope": "Jebel Irhoud morphology and evolutionary interpretation",
    "publication": {
      "title": "New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens",
      "authors": "Jean-Jacques Hublin et al.",
      "journal": "Nature 546, 289–292",
      "year": 2017,
      "doi": "10.1038/nature22336",
      "url": "https://doi.org/10.1038/nature22336"
    }
  },
  {
    "id": "nature-richter-2017",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "The age of the hominin fossils from Jebel Irhoud, Morocco, and the origins of the Middle Stone Age",
    "year": 2017,
    "authors": "Daniel Richter et al.",
    "journal": "Nature 546, 293–296",
    "doi": "10.1038/nature22335",
    "url": "https://doi.org/10.1038/nature22335",
    "role": "Dating study",
    "peerReviewed": true,
    "note": "Reports thermoluminescence and uranium-series/ESR age evidence for the Jebel Irhoud deposits.",
    "scope": "Jebel Irhoud dating",
    "publication": {
      "title": "The age of the hominin fossils from Jebel Irhoud, Morocco, and the origins of the Middle Stone Age",
      "authors": "Daniel Richter et al.",
      "journal": "Nature 546, 293–296",
      "year": 2017,
      "doi": "10.1038/nature22335",
      "url": "https://doi.org/10.1038/nature22335"
    }
  },
  {
    "id": "nature-richter-correction",
    "type": "peer-reviewed-paper",
    "publisher": "Nature",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "Author Correction: New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens",
    "year": 2018,
    "authors": "Jean-Jacques Hublin et al.",
    "journal": "Nature 558, E6",
    "doi": "10.1038/s41586-018-0166-3",
    "url": "https://doi.org/10.1038/s41586-018-0166-3",
    "role": "Published correction",
    "peerReviewed": true,
    "note": "Records published corrections to figure-axis and fossil-numbering details in the 2017 article.",
    "scope": "Jebel Irhoud publication record",
    "publication": {
      "title": "Author Correction: New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens",
      "authors": "Jean-Jacques Hublin et al.",
      "journal": "Nature 558, E6",
      "year": 2018,
      "doi": "10.1038/s41586-018-0166-3",
      "url": "https://doi.org/10.1038/s41586-018-0166-3"
    }
  },
  {
    "id": "nature-meyer-2014",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "A mitochondrial genome sequence of a hominin from Sima de los Huesos",
    "year": 2014,
    "authors": "Matthias Meyer et al.",
    "journal": "Nature 505, 403–406",
    "doi": "10.1038/nature12788",
    "url": "https://doi.org/10.1038/nature12788",
    "role": "Ancient DNA study",
    "peerReviewed": true,
    "note": "Reports an almost complete mitochondrial genome from a Sima de los Huesos hominin and its phylogenetic context.",
    "scope": "Sima de los Huesos ancient DNA",
    "publication": {
      "title": "A mitochondrial genome sequence of a hominin from Sima de los Huesos",
      "authors": "Matthias Meyer et al.",
      "journal": "Nature 505, 403–406",
      "year": 2014,
      "doi": "10.1038/nature12788",
      "url": "https://doi.org/10.1038/nature12788"
    }
  },
  {
    "id": "science-green-2010",
    "type": "primary-study",
    "publisher": "Science",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "A draft sequence of the Neandertal genome",
    "year": 2010,
    "authors": "Richard E. Green et al.",
    "journal": "Science 328(5979), 710–722",
    "doi": "10.1126/science.1188021",
    "url": "https://doi.org/10.1126/science.1188021",
    "role": "Ancient genome study",
    "peerReviewed": true,
    "note": "Presents a draft Neanderthal genome sequence and comparative analyses with modern human genomes.",
    "scope": "Neanderthal nuclear genome",
    "publication": {
      "title": "A draft sequence of the Neandertal genome",
      "authors": "Richard E. Green et al.",
      "journal": "Science 328(5979), 710–722",
      "year": 2010,
      "doi": "10.1126/science.1188021",
      "url": "https://doi.org/10.1126/science.1188021"
    }
  },
  {
    "id": "quageo-dmanisi-2010",
    "type": "primary-study",
    "publisher": "Quaternary Geochronology",
    "institution": "Collaborating geochronology and Dmanisi research teams",
    "title": "Earliest human remains in Eurasia: New 40Ar/39Ar dating of the Dmanisi hominid-bearing levels, Georgia",
    "year": 2010,
    "authors": "Tristan Garcia et al.",
    "journal": "Quaternary Geochronology 5(4), 443–451",
    "doi": "10.1016/j.quageo.2009.09.012",
    "url": "https://doi.org/10.1016/j.quageo.2009.09.012",
    "role": "Dating study",
    "peerReviewed": true,
    "note": "Reports 40Ar/39Ar dates for volcanic material associated with the Dmanisi hominin-bearing levels.",
    "scope": "Dmanisi chronology",
    "publication": {
      "title": "Earliest human remains in Eurasia: New 40Ar/39Ar dating of the Dmanisi hominid-bearing levels, Georgia",
      "authors": "Tristan Garcia et al.",
      "journal": "Quaternary Geochronology 5(4), 443–451",
      "year": 2010,
      "doi": "10.1016/j.quageo.2009.09.012",
      "url": "https://doi.org/10.1016/j.quageo.2009.09.012"
    }
  },
  {
    "id": "si-dispersal-summary",
    "type": "educational-synthesis",
    "publisher": "Natural History Museum",
    "institution": "Natural History Museum, London",
    "title": "When and how did modern humans, Homo sapiens, spread out of Africa and around the world?",
    "url": "https://www.nhm.ac.uk/discover/when-how-did-modern-humans-homo-sapiens-spread-out-of-africa.html",
    "role": "Public educational synthesis",
    "note": "Summarizes evidence for multiple dispersals and the changing picture of Homo sapiens expansion.",
    "scope": "Modern human dispersal"
  },
  {
    "id": "si-al-444-2",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "AL 444-2",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/fossils/al-444-2",
    "role": "Specimen record",
    "note": "Institutional specimen page for AL 444-2 and its Hadar context.",
    "scope": "AL 444-2 / Australopithecus afarensis"
  },
  {
    "id": "si-oh-5",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "OH 5",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/fossils/oh-5",
    "role": "Specimen record",
    "note": "Institutional specimen page for OH 5 at Olduvai Gorge.",
    "scope": "OH 5 / Paranthropus boisei"
  },
  {
    "id": "si-oh-16",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "OH 16",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/fossils/oh-16",
    "role": "Specimen record",
    "note": "Institutional specimen page for OH 16 at Olduvai Gorge.",
    "scope": "OH 16 / Homo habilis"
  },
  {
    "id": "si-singa",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Singa",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/fossils/singa",
    "role": "Specimen record",
    "note": "Institutional specimen page for the Singa cranium.",
    "scope": "Singa / Homo sapiens"
  },
  {
    "id": "si-toumai",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "TM 266-01-060-1",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/fossils/tm-266-01-060-1",
    "role": "Specimen record",
    "note": "Institutional specimen page for Toumaï from Toros-Menalla.",
    "scope": "TM 266-01-060-1 / Sahelanthropus"
  },
  {
    "id": "si-dna-first-neanderthals",
    "type": "institutional-synthesis",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "DNA and the first Neanderthals",
    "url": "https://humanorigins.si.edu/research/whats-hot-human-origins/dna-and-first-neanderthals",
    "role": "Research summary",
    "note": "Smithsonian research summary describing 430,000-year-old Sima fossils and ancient DNA evidence.",
    "scope": "Sima de los Huesos / early Neanderthal DNA"
  },
  {
    "id": "si-sts-71-3d",
    "type": "museum-3d",
    "publisher": "Smithsonian 3D Digitization",
    "institution": "Smithsonian Institution",
    "title": "Australopithecus africanus: cranium",
    "url": "https://3d.si.edu/object/3d/australopithecus-africanus-cranium%3A987cb78e-29f6-41da-be16-71a3ff2b8324",
    "role": "Museum 3D record",
    "note": "Official Smithsonian 3D record associated with STS 71.",
    "scope": "STS 71 / Australopithecus africanus"
  },
  {
    "id": "si-dnh-7-3d",
    "type": "museum-3d",
    "publisher": "Smithsonian 3D Digitization",
    "institution": "Smithsonian Institution",
    "title": "Paranthropus robustus: cranium",
    "url": "https://3d.si.edu/object/3d/paranthropus-robustus-cranium%3A8bc77140-b75c-4f96-9899-bf275b5d43dd",
    "role": "Museum 3D record",
    "note": "Official Smithsonian 3D record associated with DNH 7.",
    "scope": "DNH 7 / Paranthropus robustus"
  },
  {
    "id": "si-qafzeh-6-3d",
    "type": "museum-3d",
    "publisher": "Smithsonian 3D Digitization",
    "institution": "Smithsonian Institution",
    "title": "Homo sapiens: cranium",
    "url": "https://3d.si.edu/object/3d/homo-sapiens-cranium%3A52610788-8e81-4b0b-8d3a-8d19828236ec",
    "role": "Museum 3D record",
    "note": "Official Smithsonian 3D record for Qafzeh 6; reuse conditions are exposed by the institution.",
    "scope": "Qafzeh 6 / Homo sapiens"
  },
  {
    "id": "si-sahelanthropus-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Sahelanthropus tchadensis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/sahelanthropus-tchadensis",
    "role": "Species record",
    "note": "Institutional species page referenced by the atlas.",
    "scope": "Sahelanthropus tchadensis"
  },
  {
    "id": "si-sapiens-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Homo sapiens",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens",
    "role": "Species record",
    "note": "Institutional species page referenced by the atlas and used for Homo sapiens context.",
    "scope": "Homo sapiens"
  },
  {
    "id": "si-anamensis-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Australopithecus anamensis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/australopithecus-anamensis",
    "role": "Species record",
    "note": "Institutional species page referenced by the atlas.",
    "scope": "Australopithecus anamensis"
  },
  {
    "id": "si-naledi-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Homo naledi",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/homo-naledi",
    "role": "Species record",
    "note": "Institutional species page referenced by the atlas.",
    "scope": "Homo naledi"
  },
  {
    "id": "si-floresiensis-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Homo floresiensis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/homo-floresiensis",
    "role": "Species record",
    "note": "Institutional species page referenced by the atlas.",
    "scope": "Homo floresiensis"
  },
  {
    "id": "nature-leakey-1995",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "National Museums of Kenya / collaborating institutions",
    "title": "New four-million-year-old hominid species from Kanapoi and Allia Bay, Kenya",
    "year": 1995,
    "authors": "Meave G. Leakey et al.",
    "journal": "Nature 376, 565–571",
    "doi": "10.1038/376565a0",
    "url": "https://doi.org/10.1038/376565a0",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Names Australopithecus anamensis from Kanapoi and Allia Bay.",
    "scope": "Australopithecus anamensis type description",
    "publication": {
      "title": "New four-million-year-old hominid species from Kanapoi and Allia Bay, Kenya",
      "authors": "Meave G. Leakey et al.",
      "journal": "Nature 376, 565–571",
      "year": 1995,
      "doi": "10.1038/376565a0",
      "url": "https://doi.org/10.1038/376565a0"
    }
  },
  {
    "id": "nature-haileselassie-2019",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Cleveland Museum of Natural History / collaborating institutions",
    "title": "A 3.8-million-year-old hominin cranium from Woranso-Mille, Ethiopia",
    "year": 2019,
    "authors": "Yohannes Haile-Selassie et al.",
    "journal": "Nature 573, 214–219",
    "doi": "10.1038/s41586-019-1513-8",
    "url": "https://doi.org/10.1038/s41586-019-1513-8",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Describes the MRD-VP-1/1 cranium and argues A. anamensis and A. afarensis overlapped in time.",
    "scope": "A. anamensis cranium and the anamensis–afarensis relationship",
    "publication": {
      "title": "A 3.8-million-year-old hominin cranium from Woranso-Mille, Ethiopia",
      "authors": "Yohannes Haile-Selassie et al.",
      "journal": "Nature 573, 214–219",
      "year": 2019,
      "doi": "10.1038/s41586-019-1513-8",
      "url": "https://doi.org/10.1038/s41586-019-1513-8"
    }
  },
  {
    "id": "nature-leakey-2012",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Turkana Basin Institute / collaborating institutions",
    "title": "New fossils from Koobi Fora in northern Kenya confirm taxonomic diversity in early Homo",
    "year": 2012,
    "authors": "Meave G. Leakey et al.",
    "journal": "Nature 488, 201–204",
    "doi": "10.1038/nature11322",
    "url": "https://doi.org/10.1038/nature11322",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Reports Koobi Fora fossils associated with the KNM-ER 1470 morphology, supporting two contemporaneous early Homo lineages.",
    "scope": "Homo rudolfensis and early Homo diversity",
    "publication": {
      "title": "New fossils from Koobi Fora in northern Kenya confirm taxonomic diversity in early Homo",
      "authors": "Meave G. Leakey et al.",
      "journal": "Nature 488, 201–204",
      "year": 2012,
      "doi": "10.1038/nature11322",
      "url": "https://doi.org/10.1038/nature11322"
    }
  },
  {
    "id": "elife-berger-2015",
    "type": "primary-study",
    "publisher": "eLife",
    "institution": "University of the Witwatersrand / collaborating institutions",
    "title": "Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa",
    "year": 2015,
    "authors": "Lee R. Berger et al.",
    "journal": "eLife 4, e09560",
    "doi": "10.7554/eLife.09560",
    "url": "https://doi.org/10.7554/eLife.09560",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Names Homo naledi from the Dinaledi Chamber of the Rising Star cave system.",
    "scope": "Homo naledi type description",
    "publication": {
      "title": "Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa",
      "authors": "Lee R. Berger et al.",
      "journal": "eLife 4, e09560",
      "year": 2015,
      "doi": "10.7554/eLife.09560",
      "url": "https://doi.org/10.7554/eLife.09560"
    }
  },
  {
    "id": "elife-dirks-2017",
    "type": "primary-study",
    "publisher": "eLife",
    "institution": "University of the Witwatersrand / collaborating institutions",
    "title": "The age of Homo naledi and associated sediments in the Rising Star Cave, South Africa",
    "year": 2017,
    "authors": "Paul H. G. M. Dirks et al.",
    "journal": "eLife 6, e24231",
    "doi": "10.7554/eLife.24231",
    "url": "https://doi.org/10.7554/eLife.24231",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Dates the Dinaledi Chamber H. naledi remains to between ~335 and ~236 ka (U-series, ESR, palaeomagnetism).",
    "scope": "Homo naledi chronology",
    "publication": {
      "title": "The age of Homo naledi and associated sediments in the Rising Star Cave, South Africa",
      "authors": "Paul H. G. M. Dirks et al.",
      "journal": "eLife 6, e24231",
      "year": 2017,
      "doi": "10.7554/eLife.24231",
      "url": "https://doi.org/10.7554/eLife.24231"
    }
  },
  {
    "id": "nature-brown-2004",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "University of New England / collaborating institutions",
    "title": "A new small-bodied hominin from the Late Pleistocene of Flores, Indonesia",
    "year": 2004,
    "authors": "Peter Brown et al.",
    "journal": "Nature 431, 1055–1061",
    "doi": "10.1038/nature02999",
    "url": "https://doi.org/10.1038/nature02999",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Names Homo floresiensis from Liang Bua (LB1).",
    "scope": "Homo floresiensis type description",
    "publication": {
      "title": "A new small-bodied hominin from the Late Pleistocene of Flores, Indonesia",
      "authors": "Peter Brown et al.",
      "journal": "Nature 431, 1055–1061",
      "year": 2004,
      "doi": "10.1038/nature02999",
      "url": "https://doi.org/10.1038/nature02999"
    }
  },
  {
    "id": "nature-sutikna-2016",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "University of Wollongong / collaborating institutions",
    "title": "Revised stratigraphy and chronology for Homo floresiensis at Liang Bua in Indonesia",
    "year": 2016,
    "authors": "Thomas Sutikna et al.",
    "journal": "Nature 532, 366–369",
    "doi": "10.1038/nature17179",
    "url": "https://doi.org/10.1038/nature17179",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Revises H. floresiensis skeletal remains to ~100–60 ka and associated stone tools to ~190–50 ka.",
    "scope": "Liang Bua chronology",
    "publication": {
      "title": "Revised stratigraphy and chronology for Homo floresiensis at Liang Bua in Indonesia",
      "authors": "Thomas Sutikna et al.",
      "journal": "Nature 532, 366–369",
      "year": 2016,
      "doi": "10.1038/nature17179",
      "url": "https://doi.org/10.1038/nature17179"
    }
  },
  {
    "id": "nature-krause-2010",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "The complete mitochondrial DNA genome of an unknown hominin from southern Siberia",
    "year": 2010,
    "authors": "Johannes Krause et al.",
    "journal": "Nature 464, 894–897",
    "doi": "10.1038/nature08976",
    "url": "https://doi.org/10.1038/nature08976",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "First genetic identification of the Denisovan lineage from a Denisova Cave phalanx.",
    "scope": "Denisovan mitochondrial genome",
    "publication": {
      "title": "The complete mitochondrial DNA genome of an unknown hominin from southern Siberia",
      "authors": "Johannes Krause et al.",
      "journal": "Nature 464, 894–897",
      "year": 2010,
      "doi": "10.1038/nature08976",
      "url": "https://doi.org/10.1038/nature08976"
    }
  },
  {
    "id": "nature-reich-2010",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "Genetic history of an archaic hominin group from Denisova Cave in Siberia",
    "year": 2010,
    "authors": "David Reich et al.",
    "journal": "Nature 468, 1053–1060",
    "doi": "10.1038/nature09710",
    "url": "https://doi.org/10.1038/nature09710",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Nuclear genome of the Denisova phalanx; shows Denisovans as a sister group of Neanderthals and documents gene flow into the ancestors of present-day Melanesians.",
    "scope": "Denisovan nuclear genome and admixture",
    "publication": {
      "title": "Genetic history of an archaic hominin group from Denisova Cave in Siberia",
      "authors": "David Reich et al.",
      "journal": "Nature 468, 1053–1060",
      "year": 2010,
      "doi": "10.1038/nature09710",
      "url": "https://doi.org/10.1038/nature09710"
    }
  },
  {
    "id": "nature-chen-2019",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Lanzhou University / collaborating institutions",
    "title": "A late Middle Pleistocene Denisovan mandible from the Tibetan Plateau",
    "year": 2019,
    "authors": "Fahu Chen et al.",
    "journal": "Nature 569, 409–412",
    "doi": "10.1038/s41586-019-1139-x",
    "url": "https://doi.org/10.1038/s41586-019-1139-x",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Identifies the Xiahe mandible (≥160 ka) as Denisovan using ancient proteins.",
    "scope": "Xiahe mandible",
    "publication": {
      "title": "A late Middle Pleistocene Denisovan mandible from the Tibetan Plateau",
      "authors": "Fahu Chen et al.",
      "journal": "Nature 569, 409–412",
      "year": 2019,
      "doi": "10.1038/s41586-019-1139-x",
      "url": "https://doi.org/10.1038/s41586-019-1139-x"
    }
  },
  {
    "id": "nature-slon-2018",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Max Planck Institute for Evolutionary Anthropology / collaborating institutions",
    "title": "The genome of the offspring of a Neanderthal mother and a Denisovan father",
    "year": 2018,
    "authors": "Viviane Slon et al.",
    "journal": "Nature 561, 113–116",
    "doi": "10.1038/s41586-018-0455-x",
    "url": "https://doi.org/10.1038/s41586-018-0455-x",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Genome of Denisova 11, a first-generation Neanderthal–Denisovan offspring.",
    "scope": "Neanderthal–Denisovan gene flow",
    "publication": {
      "title": "The genome of the offspring of a Neanderthal mother and a Denisovan father",
      "authors": "Viviane Slon et al.",
      "journal": "Nature 561, 113–116",
      "year": 2018,
      "doi": "10.1038/s41586-018-0455-x",
      "url": "https://doi.org/10.1038/s41586-018-0455-x"
    }
  },
  {
    "id": "nature-johanson-1976",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "Cleveland Museum of Natural History / collaborating institutions",
    "title": "Plio-Pleistocene hominid discoveries in Hadar, Ethiopia",
    "year": 1976,
    "authors": "Donald C. Johanson & Maurice Taieb",
    "journal": "Nature 260, 293–297",
    "doi": "10.1038/260293a0",
    "url": "https://doi.org/10.1038/260293a0",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Early report of the Hadar hominin discoveries, including the A.L. 288-1 partial skeleton ('Lucy').",
    "scope": "Hadar hominins",
    "publication": {
      "title": "Plio-Pleistocene hominid discoveries in Hadar, Ethiopia",
      "authors": "Donald C. Johanson & Maurice Taieb",
      "journal": "Nature 260, 293–297",
      "year": 1976,
      "doi": "10.1038/260293a0",
      "url": "https://doi.org/10.1038/260293a0"
    }
  },
  {
    "id": "nature-dart-1925",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "University of the Witwatersrand",
    "title": "Australopithecus africanus: the man-ape of South Africa",
    "year": 1925,
    "authors": "Raymond A. Dart",
    "journal": "Nature 115, 195–199",
    "doi": "10.1038/115195a0",
    "url": "https://doi.org/10.1038/115195a0",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Names Australopithecus africanus from the Taung child skull.",
    "scope": "Taung 1 and the naming of Australopithecus",
    "publication": {
      "title": "Australopithecus africanus: the man-ape of South Africa",
      "authors": "Raymond A. Dart",
      "journal": "Nature 115, 195–199",
      "year": 1925,
      "doi": "10.1038/115195a0",
      "url": "https://doi.org/10.1038/115195a0"
    }
  },
  {
    "id": "science-white-2009",
    "type": "primary-study",
    "publisher": "Science",
    "institution": "University of California, Berkeley / collaborating institutions",
    "title": "Ardipithecus ramidus and the paleobiology of early hominids",
    "year": 2009,
    "authors": "Tim D. White et al.",
    "journal": "Science 326(5949), 64–86",
    "doi": "10.1126/science.1175802",
    "url": "https://doi.org/10.1126/science.1175802",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Synthesis of the Ar. ramidus record, including the ARA-VP-6/500 partial skeleton ('Ardi').",
    "scope": "Ardipithecus ramidus paleobiology",
    "publication": {
      "title": "Ardipithecus ramidus and the paleobiology of early hominids",
      "authors": "Tim D. White et al.",
      "journal": "Science 326(5949), 64–86",
      "year": 2009,
      "doi": "10.1126/science.1175802",
      "url": "https://doi.org/10.1126/science.1175802"
    }
  },
  {
    "id": "nature-brown-1985",
    "type": "primary-study",
    "publisher": "Nature",
    "institution": "National Museums of Kenya / collaborating institutions",
    "title": "Early Homo erectus skeleton from west Lake Turkana, Kenya",
    "year": 1985,
    "authors": "Frank Brown et al.",
    "journal": "Nature 316, 788–792",
    "doi": "10.1038/316788a0",
    "url": "https://doi.org/10.1038/316788a0",
    "role": "Primary research",
    "peerReviewed": true,
    "note": "Reports the KNM-WT 15000 ('Turkana Boy') skeleton from Nariokotome.",
    "scope": "KNM-WT 15000",
    "publication": {
      "title": "Early Homo erectus skeleton from west Lake Turkana, Kenya",
      "authors": "Frank Brown et al.",
      "journal": "Nature 316, 788–792",
      "year": 1985,
      "doi": "10.1038/316788a0",
      "url": "https://doi.org/10.1038/316788a0"
    }
  },
  {
    "id": "si-orrorin-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Orrorin tugenensis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/orrorin-tugenensis",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Orrorin tugenensis"
  },
  {
    "id": "si-ardipithecus-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Ardipithecus ramidus",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/ardipithecus-ramidus",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Ardipithecus ramidus"
  },
  {
    "id": "si-afarensis-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Australopithecus afarensis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/australopithecus-afarensis",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Australopithecus afarensis"
  },
  {
    "id": "si-africanus-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Australopithecus africanus",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/australopithecus-africanus",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Australopithecus africanus"
  },
  {
    "id": "si-boisei-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Paranthropus boisei",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/paranthropus-boisei",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Paranthropus boisei"
  },
  {
    "id": "si-robustus-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Paranthropus robustus",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/paranthropus-robustus",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Paranthropus robustus"
  },
  {
    "id": "si-habilis-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Homo habilis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/homo-habilis",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Homo habilis"
  },
  {
    "id": "si-erectus-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Homo erectus",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/homo-erectus",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Homo erectus"
  },
  {
    "id": "si-heidelbergensis-species",
    "type": "institutional-record",
    "publisher": "Smithsonian Human Origins Program",
    "institution": "Smithsonian Institution",
    "title": "Homo heidelbergensis",
    "url": "https://humanorigins.si.edu/evidence/human-fossils/species/homo-heidelbergensis",
    "role": "Species record",
    "note": "Institutional species page; reference for the key facts (time range, body and brain size, diet, key fossils) shown in the atlas.",
    "scope": "Homo heidelbergensis"
  }
] as const
const institutionIdFromName=(value?:string)=>{
  if(!value) return undefined
  const normalized=value.toLowerCase()
  if(normalized.includes('smithsonian')) return asInstitutionId('smithsonian-institution')
  if(normalized.includes('max planck')) return asInstitutionId('max-planck-eva')
  if(normalized.includes('natural history museum')) return asInstitutionId('natural-history-museum-london')
  if(normalized.includes('witwatersrand')) return asInstitutionId('university-witwatersrand')
  if(normalized.includes('georgian national museum')) return asInstitutionId('georgian-national-museum')
  if(normalized.includes('national museum of tanzania')) return asInstitutionId('national-museum-tanzania')
  if(normalized.includes('national museum of ethiopia')) return asInstitutionId('national-museum-ethiopia')
  if(normalized.includes('institut de paléontologie humaine')) return asInstitutionId('institut-paleontologie-humaine')
  return undefined
}
const publicationIdBySourceId:Record<string,ReturnType<typeof asPublicationId>>={
  'nature-hublin-2017':asPublicationId('pub-hublin-2017'),
  'nature-richter-2017':asPublicationId('pub-richter-2017'),
  'nature-richter-correction':asPublicationId('pub-hublin-correction-2018'),
  'nature-meyer-2014':asPublicationId('pub-meyer-2014'),
  'science-green-2010':asPublicationId('pub-green-2010'),
  'quageo-dmanisi-2010':asPublicationId('pub-garcia-2010'),
  'nature-johanson-1976':asPublicationId('pub-johanson-1976'),
  'nature-dart-1925':asPublicationId('pub-dart-1925'),
  'science-white-2009':asPublicationId('pub-white-2009'),
  'nature-brown-1985':asPublicationId('pub-brown-1985'),
  'nature-leakey-1995':asPublicationId('pub-leakey-1995'),
  'nature-haileselassie-2019':asPublicationId('pub-haileselassie-2019'),
  'nature-leakey-2012':asPublicationId('pub-leakey-2012'),
  'elife-berger-2015':asPublicationId('pub-berger-2015'),
  'elife-dirks-2017':asPublicationId('pub-dirks-2017'),
  'nature-brown-2004':asPublicationId('pub-brown-2004'),
  'nature-sutikna-2016':asPublicationId('pub-sutikna-2016'),
  'nature-krause-2010':asPublicationId('pub-krause-2010'),
  'nature-reich-2010':asPublicationId('pub-reich-2010'),
  'nature-chen-2019':asPublicationId('pub-chen-2019'),
  'nature-slon-2018':asPublicationId('pub-slon-2018'),
}
export const sourceRecords:SourceRecord[]=rawSources.map(item=>{
  const institutionId=institutionIdFromName(item.institution)
  const publicationId=publicationIdBySourceId[item.id]
  const doi='doi' in item ? item.doi : undefined
  const identifiers=[
    ...(doi?[{scheme:'doi' as const,value:doi,uri:item.url,preferred:true,verification:'verified' as const,origin:'publisher' as const}]:[]),
    {scheme:'uri' as const,value:item.url,uri:item.url,label:'Canonical source URL',verification:'asserted' as const,origin:'curatorial' as const},
  ]
  return {
    id:asSourceId(item.id),
    type:item.type,
    publisher:item.publisher,
    title:item.title,
    url:item.url,
    role:item.role,
    note:item.note,
    scope:item.scope,
    institutionId,
    publicationId,
    identifiers,
    peerReviewed:'peerReviewed' in item ? item.peerReviewed : undefined,
  } as SourceRecord
})
export const sourcesById=Object.fromEntries(sourceRecords.map(source=>[String(source.id),source])) as Record<string,SourceRecord>
export const sourceIdByUrl=Object.fromEntries(sourceRecords.map(source=>[source.url,String(source.id)])) as Record<string,string>
export type {SourceRecord}
