import type {MaterialEntityRecord,SpecimenRecord} from '../domain/contracts'
import {asInstitutionId,asMaterialEntityId,asOccurrenceId,asSiteId,asSourceId,asSpecimenId,asTaxonId} from '../domain/ids'

const rawSpecimens=[
  {
    "id": "neanderthal-1",
    "taxonId": "neanderthal",
    "name": "Neanderthal 1",
    "objectIdentifier": "Feldhofer 1",
    "siteId": "feldhofer",
    "siteLabel": "Feldhofer Cave · Neander Valley",
    "country": "Germany",
    "ageLabel": "About 40,000 years",
    "evidence": "Fossil",
    "significance": "Discovered in 1856, this was the first fossil recognized as an early human and became the type specimen for Homo neanderthalensis.",
    "sourceId": "si-feldhofer",
    "viewerUrl": "https://3d.si.edu/object/3d/homo-neanderthalensis-cranium%3A5b3ead12-0fb2-4a9b-b5bf-b7a92be656e8",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "Rheinisches Landesmuseum Bonn (Germany)",
    "discoveryYear": "1856",
    "recordId": "dpo_3d_200096",
    "metadataUsage": "Usage conditions apply"
  },
  {
    "id": "sima-hominins",
    "taxonId": "neanderthal",
    "name": "Sima de los Huesos fossils",
    "siteId": "sima-los-huesos",
    "siteLabel": "Sima de los Huesos · Atapuerca",
    "country": "Spain",
    "ageLabel": "~430,000 years",
    "evidence": "Ancient DNA",
    "significance": "Ancient DNA from Sima fossils provides evidence relevant to early Neanderthal lineage history.",
    "sourceId": "si-dna-first-neanderthals"
  },
  {
    "id": "vindija-1",
    "taxonId": "neanderthal",
    "name": "Vindija Neanderthals",
    "siteId": "vindija",
    "siteLabel": "Vindija Cave",
    "country": "Croatia",
    "ageLabel": "~44,000 years for sequenced samples",
    "evidence": "Ancient DNA",
    "significance": "Vindija material contributed to early Neanderthal mitochondrial and nuclear genome studies.",
    "sourceId": "si-neanderthal-dna"
  },
  {
    "id": "jebel-irhoud",
    "taxonId": "sapiens",
    "name": "Jebel Irhoud fossils",
    "siteId": "jebel-irhoud",
    "siteLabel": "Jebel Irhoud",
    "country": "Morocco",
    "ageLabel": "~300,000 years",
    "evidence": "Fossil",
    "significance": "The Moroccan fossils are among the oldest currently known Homo sapiens remains.",
    "sourceId": "si-sapiens-300ka"
  },
  {
    "id": "singa",
    "taxonId": "sapiens",
    "name": "Singa",
    "objectIdentifier": "Singa",
    "siteId": "singa",
    "siteLabel": "Singa",
    "country": "Sudan",
    "ageLabel": "120,000–150,000 years",
    "evidence": "Fossil",
    "significance": "A Smithsonian 3D record for a Homo sapiens cranium from Singa, Sudan.",
    "sourceId": "si-singa",
    "viewerUrl": "https://3d.si.edu/object/3d/homo-sapiens-cranium%3A4361860d-2475-4765-bbff-f3c41deeb8c7",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "Natural History Museum (England)",
    "discoveryYear": "1924",
    "recordId": "dpo_3d_200078",
    "metadataUsage": "CC0"
  },
  {
    "id": "d2282",
    "taxonId": "erectus",
    "name": "D2282",
    "objectIdentifier": "D2282",
    "siteId": "dmanisi",
    "siteLabel": "Dmanisi",
    "country": "Georgia",
    "ageLabel": "~1.77 million years",
    "evidence": "Fossil",
    "significance": "One of the earliest known Homo skulls outside Africa, documenting an early dispersal of Homo into Eurasia.",
    "sourceId": "si-d2282",
    "viewerUrl": "https://3d.si.edu/object/3d/homo-erectus-cranium%3A0b1d7e98-3dd0-4614-93d7-a2ae3cc9b11c",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "Georgian National Museum (Republic of Georgia)",
    "discoveryYear": "1999",
    "recordId": "dpo_3d_200045",
    "metadataUsage": "CC0"
  },
  {
    "id": "toumai",
    "taxonId": "sahelanthropus",
    "name": "TM 266-01-060-1 · Toumaï",
    "objectIdentifier": "TM 266-01-060-1",
    "siteId": "toros-menalla",
    "siteLabel": "Toros-Menalla",
    "country": "Chad",
    "ageLabel": "Between 7 and 6 million years",
    "evidence": "Fossil",
    "significance": "A nearly complete, distorted cranium central to research on the earliest stages of the human lineage.",
    "sourceId": "si-toumai",
    "viewerUrl": "https://3d.si.edu/object/3d/sahelanthropus-tchadensis-cranium%3A9730a62f-a649-44fb-8494-aa7c9b6eb1f8",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "Centre National d’Appui à la Recherche / National Center of Research Support (Chad)",
    "discoveryYear": "2001",
    "recordId": "dpo_3d_200071",
    "metadataUsage": "CC0"
  },
  {
    "id": "al-444-2",
    "taxonId": "afarensis",
    "name": "AL 444-2",
    "objectIdentifier": "A.L. 444-2",
    "siteId": "hadar",
    "siteLabel": "Hadar",
    "country": "Ethiopia",
    "ageLabel": "About 3 million years",
    "evidence": "Fossil",
    "significance": "A large male Australopithecus afarensis cranium from the same locality as the famous Lucy skeleton.",
    "sourceId": "si-al-444-2",
    "viewerUrl": "https://3d.si.edu/object/3d/australopithecus-afarensis-cranium%3A6faf8121-250c-47cb-a5cc-139d7b16c570",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "National Museum of Ethiopia (Ethiopia)",
    "discoveryYear": "1992",
    "recordId": "dpo_3d_200040",
    "metadataUsage": "CC0"
  },
  {
    "id": "sts-71",
    "taxonId": "africanus",
    "name": "STS 71",
    "objectIdentifier": "STS 71",
    "siteId": "sterkfontein",
    "siteLabel": "Sterkfontein",
    "country": "South Africa",
    "ageLabel": "2.8–2.4 million years",
    "evidence": "Fossil",
    "significance": "A well-known Australopithecus africanus cranium from Sterkfontein.",
    "sourceId": "si-sts-71-3d",
    "viewerUrl": "https://3d.si.edu/object/3d/australopithecus-africanus-cranium%3A987cb78e-29f6-41da-be16-71a3ff2b8324",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "University of the Witwatersrand (South Africa)",
    "discoveryYear": "1947",
    "recordId": "dpo_3d_200042",
    "metadataUsage": "CC0"
  },
  {
    "id": "oh-5",
    "taxonId": "boisei",
    "name": "OH 5 · “Zinj”",
    "objectIdentifier": "OH 5",
    "siteId": "olduvai",
    "siteLabel": "Olduvai Gorge",
    "country": "Tanzania",
    "ageLabel": "About 1.8 million years",
    "evidence": "Fossil",
    "significance": "The nearly complete cranium made famous by Mary Leakey’s 1959 discovery and later designated the type specimen for Paranthropus boisei.",
    "sourceId": "si-oh-5",
    "viewerUrl": "https://3d.si.edu/object/3d/paranthropus-boisei-cranium%3Af71256ba-fb5d-4a26-b44d-3d4cc2a8b533",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "National Museum of Tanzania",
    "discoveryYear": "1959",
    "recordId": "dpo_3d_200074",
    "metadataUsage": "CC0"
  },
  {
    "id": "dnh-7",
    "taxonId": "robustus",
    "name": "DNH 7",
    "objectIdentifier": "DNH 7",
    "siteId": "drimolen",
    "siteLabel": "Drimolen Main Quarry",
    "country": "South Africa",
    "ageLabel": "2.04–1.95 million years",
    "evidence": "Fossil",
    "significance": "A particularly complete Paranthropus robustus cranium, with parts of the mandible preserved.",
    "sourceId": "si-dnh-7-3d",
    "viewerUrl": "https://3d.si.edu/object/3d/paranthropus-robustus-cranium%3A8bc77140-b75c-4f96-9899-bf275b5d43dd",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "University of the Witwatersrand (South Africa)",
    "discoveryYear": "1994",
    "recordId": "dpo_3d_200073",
    "metadataUsage": "Usage conditions apply"
  },
  {
    "id": "oh-16",
    "taxonId": "habilis",
    "name": "OH 16",
    "objectIdentifier": "OH 16",
    "siteId": "olduvai",
    "siteLabel": "Olduvai Gorge",
    "country": "Tanzania",
    "ageLabel": "About 1.7 million years",
    "evidence": "Fossil",
    "significance": "A crushed Homo habilis skull used in the original recognition of the species.",
    "sourceId": "si-oh-16",
    "viewerUrl": "https://3d.si.edu/object/3d/homo-habilis-cranium%3A05a42feb-46d0-45b1-8726-be7193367859",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "National Museum of Tanzania",
    "discoveryYear": "1963",
    "recordId": "dpo_3d_200062",
    "metadataUsage": "CC0"
  },
  {
    "id": "qafzeh-6",
    "taxonId": "sapiens",
    "name": "Qafzeh 6",
    "objectIdentifier": "Qafzeh 6",
    "siteId": "levant",
    "siteLabel": "Jebel Qafzeh",
    "country": "Israel",
    "ageLabel": "About 100,000 years",
    "evidence": "Fossil",
    "significance": "A Homo sapiens cranium from the Jebel Qafzeh site in the Levant.",
    "sourceId": "si-qafzeh-6-3d",
    "viewerUrl": "https://3d.si.edu/object/3d/homo-sapiens-cranium%3A52610788-8e81-4b0b-8d3a-8d19828236ec",
    "viewerLabel": "Smithsonian 3D viewer",
    "originalInstitution": "Institut de Paléontologie Humaine (France)",
    "discoveryYear": "1933",
    "recordId": "dpo_3d_200079",
    "metadataUsage": "CC0"
  },
  {
    "id": "al-288-1",
    "taxonId": "afarensis",
    "name": "Lucy",
    "objectIdentifier": "A.L. 288-1",
    "siteId": "hadar",
    "siteLabel": "Hadar",
    "country": "Ethiopia",
    "ageLabel": "About 3.2 million years",
    "evidence": "Fossil",
    "significance": "About 40% of a single skeleton; one of the most complete early hominins and key evidence that A. afarensis walked upright.",
    "sourceId": "nature-johanson-1976",
    "discoveryYear": "1974",
    "originalInstitution": "National Museum of Ethiopia (Ethiopia)"
  },
  {
    "id": "taung-1",
    "taxonId": "africanus",
    "name": "Taung child",
    "objectIdentifier": "Taung 1",
    "siteId": "taung",
    "siteLabel": "Taung",
    "country": "South Africa",
    "ageLabel": "~2.8–2.6 Ma (debated)",
    "evidence": "Fossil",
    "significance": "Juvenile skull and natural brain endocast used by Raymond Dart in 1925 to name Australopithecus africanus.",
    "sourceId": "nature-dart-1925",
    "discoveryYear": "1924",
    "originalInstitution": "University of the Witwatersrand (South Africa)"
  },
  {
    "id": "ara-vp-6-500",
    "taxonId": "ardipithecus",
    "name": "Ardi",
    "objectIdentifier": "ARA-VP-6/500",
    "siteId": "aramis",
    "siteLabel": "Aramis · Middle Awash",
    "country": "Ethiopia",
    "ageLabel": "About 4.4 million years",
    "evidence": "Fossil",
    "significance": "Partial skeleton of a female Ar. ramidus combining bipedal features with a grasping big toe.",
    "sourceId": "science-white-2009",
    "discoveryYear": "1994",
    "originalInstitution": "National Museum of Ethiopia (Ethiopia)"
  },
  {
    "id": "knm-wt-15000",
    "taxonId": "ergaster",
    "name": "Turkana Boy",
    "objectIdentifier": "KNM-WT 15000",
    "siteId": "nariokotome",
    "siteLabel": "Nariokotome · West Turkana",
    "country": "Kenya",
    "ageLabel": "About 1.5 million years",
    "evidence": "Fossil",
    "significance": "The most complete early Homo skeleton known; a juvenile assigned to H. ergaster / early African H. erectus.",
    "sourceId": "nature-brown-1985",
    "discoveryYear": "1984"
  },
  {
    "id": "knm-kp-29281",
    "taxonId": "anamensis",
    "name": "KNM-KP 29281 (holotype)",
    "objectIdentifier": "KNM-KP 29281",
    "siteId": "kanapoi",
    "siteLabel": "Kanapoi",
    "country": "Kenya",
    "ageLabel": "About 4.1 million years",
    "evidence": "Fossil",
    "significance": "Mandible designated as the holotype of Australopithecus anamensis.",
    "sourceId": "nature-leakey-1995",
    "discoveryYear": "1994"
  },
  {
    "id": "dh1",
    "taxonId": "naledi",
    "name": "DH1 (holotype)",
    "objectIdentifier": "DH1",
    "siteId": "rising-star",
    "siteLabel": "Dinaledi Chamber · Rising Star",
    "country": "South Africa",
    "ageLabel": "~335–236 ka",
    "evidence": "Fossil",
    "significance": "Partial cranium and mandible designated as the holotype of Homo naledi.",
    "sourceId": "elife-berger-2015",
    "discoveryYear": "2013",
    "originalInstitution": "University of the Witwatersrand (South Africa)"
  },
  {
    "id": "lb1",
    "taxonId": "floresiensis",
    "name": "LB1",
    "objectIdentifier": "LB1",
    "siteId": "liang-bua",
    "siteLabel": "Liang Bua",
    "country": "Indonesia",
    "ageLabel": "~100–60 ka",
    "evidence": "Fossil",
    "significance": "Partial skeleton of a ~1.1 m tall adult; holotype of Homo floresiensis.",
    "sourceId": "nature-brown-2004",
    "discoveryYear": "2003"
  },
  {
    "id": "denisova-3",
    "taxonId": "denisovan",
    "name": "Denisova 3",
    "objectIdentifier": "Denisova 3",
    "siteId": "altai",
    "siteLabel": "Denisova Cave",
    "country": "Russia",
    "ageLabel": "~76–52 ka",
    "evidence": "Ancient DNA",
    "significance": "Finger-bone fragment whose DNA first revealed the Denisovan lineage.",
    "sourceId": "nature-krause-2010",
    "discoveryYear": "2008"
  },
  {
    "id": "xiahe-mandible",
    "taxonId": "denisovan",
    "name": "Xiahe mandible",
    "objectIdentifier": "Xiahe mandible",
    "siteId": "baishiya",
    "siteLabel": "Baishiya Karst Cave",
    "country": "China",
    "ageLabel": "≥160 ka",
    "evidence": "Fossil",
    "significance": "Partial mandible identified as Denisovan from ancient proteins; the first Denisovan fossil outside Denisova Cave.",
    "sourceId": "nature-chen-2019",
    "discoveryYear": "1980"
  }
] as const
const institutionIdByName:Record<string,ReturnType<typeof asInstitutionId>>={
  'Rheinisches Landesmuseum Bonn (Germany)':asInstitutionId('rheinisches-landesmuseum-bonn'),
  'Natural History Museum (England)':asInstitutionId('natural-history-museum-london'),
  'Georgian National Museum (Republic of Georgia)':asInstitutionId('georgian-national-museum'),
  'National Museum of Ethiopia (Ethiopia)':asInstitutionId('national-museum-ethiopia'),
  'National Museum of Tanzania':asInstitutionId('national-museum-tanzania'),
  'University of the Witwatersrand (South Africa)':asInstitutionId('university-witwatersrand'),
  'Institut de Paléontologie Humaine (France)':asInstitutionId('institut-paleontologie-humaine'),
  'Centre National d’Appui à la Recherche / National Center of Research Support (Chad)':asInstitutionId('centre-national-appui-recherche-chad'),
}

export const materialEntityRecords:MaterialEntityRecord[]=rawSpecimens.map(item=>({
  id:asMaterialEntityId(`material-${item.id}`),
  materialType:'fossil' as const,
  taxonId:asTaxonId(item.taxonId),
  objectIdentifier:'objectIdentifier' in item ? item.objectIdentifier : undefined,
  institutionId:'originalInstitution' in item && item.originalInstitution ? institutionIdByName[item.originalInstitution] : undefined,
  collectionId:undefined,
  catalogNumber:'objectIdentifier' in item ? item.objectIdentifier : undefined,
  objectType:'hominin fossil material',
  basisOfRecord:'FossilSpecimen' as const,
  viewerUrl:'viewerUrl' in item ? item.viewerUrl : undefined,
  viewerLabel:'viewerLabel' in item ? item.viewerLabel : undefined,
  originalInstitution:'originalInstitution' in item ? item.originalInstitution : undefined,
  discoveryYear:'discoveryYear' in item ? item.discoveryYear : undefined,
  recordId:'recordId' in item ? item.recordId : undefined,
  metadataUsage:'metadataUsage' in item ? item.metadataUsage : undefined,
  sourceIds:[asSourceId(item.sourceId)],
  sourceLinks:[{sourceId:asSourceId(item.sourceId),role:'catalogues' as const}],
  identifiers:'objectIdentifier' in item && item.objectIdentifier ? [{scheme:'catalog-number' as const,value:item.objectIdentifier,label:'Catalog / object identifier',verification:'asserted' as const,origin:'institutional-record' as const}] : [],
}))

export const specimenRecords:SpecimenRecord[]=rawSpecimens.map(item=>({
  id:asSpecimenId(item.id),
  taxonId:asTaxonId(item.taxonId),
  name:item.name,
  siteId:asSiteId(item.siteId),
  ageLabel:item.ageLabel,
  evidence:item.evidence,
  significance:item.significance,
  sourceIds:[asSourceId(item.sourceId)],
  sourceLinks:[{sourceId:asSourceId(item.sourceId),role:'documents' as const}],
  occurrenceId:asOccurrenceId(`occ-${item.id}`),
  materialEntityId:asMaterialEntityId(`material-${item.id}`),
  publicationIds:[],
  discoveryYear:'discoveryYear' in item ? item.discoveryYear : undefined,
  imageUrl:'imageUrl' in item && typeof item.imageUrl==='string' ? item.imageUrl : undefined,
  imageAlt:'imageAlt' in item && typeof item.imageAlt==='string' ? item.imageAlt : undefined,
  imageCredit:'imageCredit' in item && typeof item.imageCredit==='string' ? item.imageCredit : undefined,
}))

export const specimensById=Object.fromEntries(specimenRecords.map(item=>[String(item.id),item])) as Record<string,SpecimenRecord>
export const materialEntitiesById=Object.fromEntries(materialEntityRecords.map(item=>[String(item.id),item])) as Record<string,MaterialEntityRecord>
