import {mkdirSync,writeFileSync} from 'node:fs'
import {dirname,join} from 'node:path'
import {buildCatalog,composePromptFiles,type CatalogRow} from './spec'

const root=join(process.cwd(),'tools/images')
export const SLOTS_FILE='content/media-slots.generated.ts'
const csvCell=(value:string|number|null)=>`"${String(value??'').replace(/"/g,'""')}"`
const COLUMNS:(keyof CatalogRow)[]=['code','taxonId','series','title','role','mediaKind','evidenceClass','wave','ratio','size','status','statusReason','specimenRef','brief','promptFile']

export function renderCatalogFiles(){
  const rows=buildCatalog()
  return {
    'catalog.json':JSON.stringify(rows,null,2)+'\n',
    'catalog.csv':[COLUMNS.join(','),...rows.map(row=>COLUMNS.map(column=>csvCell(row[column] as string|number|null)).join(','))].join('\n')+'\n',
  }
}

const q=(value:string)=>JSON.stringify(value)

/** content/media-slots.generated.ts: one typed slot definition per applicable-or-not catalog row. */
export function renderSlotsFile():string{
  const rows=buildCatalog()
  const lines=rows.map(row=>{
    const size=/(\d+)×(\d+)/.exec(row.size)
    const widthOnly=/(\d+) px/.exec(row.size)
    const width=size?Number(size[1]):widthOnly?Number(widthOnly[1]):null
    const height=size?Number(size[2]):null
    const applicable=row.status!=='NOT-APPLICABLE'
    const publicRule=row.series==='S02'||row.series==='S03'?'always':'whenFilled'
    const holdReason=row.status==='BLOCKED-NO-SPECIMEN'?row.statusReason:''
    return `  {id:slot(${q(row.code)}),taxonId:${row.taxonId?`taxon(${q(row.taxonId)})`:'null'},series:${q(row.series)},title:${q(row.title)},role:${q(row.role)},kind:${q(row.mediaKind)},evidenceClass:${q(row.evidenceClass)},ratio:${q(row.ratio)},width:${width},height:${height},applicable:${applicable},notApplicableReason:${q(applicable?'':row.statusReason)},publicRule:${q(publicRule)},needsReview:${row.evidenceClass==='D'},holdReason:${q(holdReason)}},`
  })
  return `/* GENERATED by \`npm run images:build\` from tools/images (taxa.ts, spec.ts). Do not edit by hand. */
import {asMediaSlotId as slot,asTaxonId as taxon} from '../domain/ids'
import type {MediaSlotDefinition} from '../domain/media-slots'

export const MEDIA_SLOTS:readonly MediaSlotDefinition[]=[
${lines.join('\n')}
]
`
}

function main(){
  const files={...renderCatalogFiles(),...composePromptFiles()}
  for(const [name,content] of Object.entries(files)){
    const target=join(root,name)
    mkdirSync(dirname(target),{recursive:true})
    writeFileSync(target,content)
  }
  const slotsTarget=join(process.cwd(),SLOTS_FILE)
  writeFileSync(slotsTarget,renderSlotsFile())
  console.log(`images:build wrote ${Object.keys(files).length+1} files`)
}

if(process.argv[1]&&/build\.(ts|js)$/.test(process.argv[1])) main()
