import {TAXA,type TaxonBrief} from './taxa'

/**
 * Image production plan: the master catalog (200 rows) and the self-contained prompts for class-D images.
 * Pure functions only; `build.ts` writes the outputs and `tests/image-plan.test.ts` keeps them honest.
 *
 * Evidence classes: A generated by code from sourced data · B code + licensed scan/template · C licensed photograph or
 * scan render of a real specimen (NEVER generated by AI) · D reconstruction made by an artist/3D or a generator from this brief.
 */
export type EvidenceClass='A'|'B'|'C'|'D'
export type RowStatus='TODO'|'BLOCKED-NO-SPECIMEN'|'NOT-APPLICABLE'
export type MediaKindName='specimen-photo'|'cast-photo'|'reconstruction'|'context-schematic'
export type CatalogRow={
  code:string;taxonId:string|null;series:string;title:string;role:string;mediaKind:MediaKindName;evidenceClass:EvidenceClass
  wave:1|2|3|4|5|6;ratio:string;size:string;status:RowStatus;statusReason:string;specimenRef:string;brief:string;promptFile:string
}

export const CORE_TAXA_ORDER=TAXA.map(taxon=>taxon.id)

const FORMAT={
  square:{ratio:'1:1',size:'512×512'},portrait:{ratio:'4:5',size:'1000×1250'},hero:{ratio:'16:9',size:'1920×1080'},
  plate:{ratio:'4:3',size:'1600×1200'},vector:{ratio:'free (SVG)',size:'vector + 1600 px WebP fallback'},card:{ratio:'1.91:1',size:'1200×630'},
} as const

type Series={code:string;title:(t:TaxonBrief)=>string;role:string;kind:MediaKindName;cls:EvidenceClass;wave:1|2|3;fmt:keyof typeof FORMAT;brief:(t:TaxonBrief)=>string}

const SOURCE_ORDER='Source order: (1) museum or institutional open-access collections, (2) licensed 3D scan repositories (e.g. MorphoSource, Smithsonian) with an explicit licence, (3) Wikimedia Commons with a CC licence. Record institution, catalog number, licence, credit and source URL. Never AI-generated; if no licensed image exists, leave the slot empty.'
const PLATE_RULES='Neutral dark-grey background, even lighting, scale bar in centimetres, specimen in standard orientation (skull on the Frankfurt horizontal plane).'

const SERIES:Series[]=[
  {code:'S01',title:t=>`${t.short}: tree avatar`,role:'tree-thumbnail',kind:'context-schematic',cls:'B',wave:1,fmt:'square',
    brief:t=>`Render of the primary cranium (${t.basis.primary}) in lateral view, square crop, identical camera, light and background preset for all 11 core taxa, legible at 36 px. Built from a licensed scan or cast photograph (see S04 sources); no AI. Must differ visibly from the portrait.`},
  {code:'S02',title:t=>`${t.short}: portrait`,role:'profile-portrait',kind:'reconstruction',cls:'D',wave:1,fmt:'portrait',
    brief:t=>t.noCranium?'Bone-inventory silhouette (no face is rendered because no cranium exists). Prompt provided.':'Scientific facial reconstruction from the cranium. Prompt provided. Requires reference renders (S04/S05), assumptions sheet and review.'},
  {code:'S03',title:t=>`${t.short}: dossier hero`,role:'dossier-hero',kind:'reconstruction',cls:'D',wave:2,fmt:'hero',
    brief:()=>'Wide environmental scene with 2–3 individuals. Prompt provided. Requires assumptions sheet and review.'},
  {code:'S04',title:t=>`${t.short}: cranium, lateral view`,role:'specimen-reference',kind:'specimen-photo',cls:'C',wave:1,fmt:'plate',
    brief:t=>`Lateral view of ${t.basis.primary}. ${PLATE_RULES} ${SOURCE_ORDER}`},
  {code:'S05',title:t=>`${t.short}: cranium, frontal view`,role:'specimen-reference',kind:'specimen-photo',cls:'C',wave:1,fmt:'plate',
    brief:t=>`Frontal view of ${t.basis.primary}. ${PLATE_RULES} ${SOURCE_ORDER}`},
  {code:'S06',title:t=>`${t.short}: jaw and teeth, occlusal view`,role:'specimen-reference',kind:'specimen-photo',cls:'C',wave:2,fmt:'plate',
    brief:t=>`Occlusal view of the best-preserved mandible or maxilla of ${t.short} (${[t.basis.primary,...t.basis.also].join('; ')}). ${PLATE_RULES} ${SOURCE_ORDER}`},
  {code:'S07a',title:t=>`${t.short}: key bone 1 — ${t.keyBones[0]}`,role:'anatomy-plate',kind:'specimen-photo',cls:'C',wave:2,fmt:'plate',
    brief:t=>`${t.keyBones[0]}. ${PLATE_RULES} ${SOURCE_ORDER}`},
  {code:'S07b',title:t=>`${t.short}: key bone 2 — ${t.keyBones[1]}`,role:'anatomy-plate',kind:'specimen-photo',cls:'C',wave:2,fmt:'plate',
    brief:t=>`${t.keyBones[1]}. ${PLATE_RULES} ${SOURCE_ORDER}`},
  {code:'S08',title:t=>`${t.short}: annotated anatomy diagram`,role:'anatomy-plate',kind:'context-schematic',cls:'B',wave:3,fmt:'vector',
    brief:t=>`Vector diagram traced from the S04/S05 images. Label at most six diagnostic traits, each backed by a sourced claim: ${t.diagnostic.join('; ')}. Label text comes from claim records, not free text.`},
  {code:'S09',title:t=>`${t.short}: scale against an adult human`,role:'scale-reference',kind:'context-schematic',cls:'A',wave:3,fmt:'vector',
    brief:t=>`Generated by script: height and mass drawn as uncertainty BANDS next to a 170 cm adult-human silhouette, labelled “estimate”. Source ranges: ${t.body}. No individual-looking figure.`},
  {code:'S10',title:t=>`${t.short}: habitat`,role:'habitat',kind:'reconstruction',cls:'D',wave:1,fmt:'hero',
    brief:()=>'Paleoenvironment landscape with NO hominins. Prompt provided. Fauna kinds must be verified against the site faunal list.'},
  {code:'S11',title:t=>`${t.short}: ${t.behavior?t.behavior.title:'behaviour'}`,role:'behavior',kind:'reconstruction',cls:'D',wave:3,fmt:'plate',
    brief:t=>t.behavior?'Behaviour scene limited to what the evidence documents. Prompt provided.':'No source-supported behaviour exists; the slot stays empty until evidence is registered.'},
  {code:'S12',title:t=>`${t.short}: type or principal site`,role:'context',kind:'specimen-photo',cls:'C',wave:2,fmt:'hero',
    brief:t=>`Photograph of ${t.typeSite} (landscape or excavation). Licensed; if none exists, use a licensed landscape photograph with a site marker and say so in the caption. ${SOURCE_ORDER}`},
  {code:'S13',title:t=>`${t.short}: sites and range map`,role:'context',kind:'context-schematic',cls:'A',wave:1,fmt:'vector',
    brief:t=>`Generated by script from the site records linked to ${t.short} and the paleo pipeline (phase P3) at the taxon's time slice; uncertainty drawn as soft areas.`},
  {code:'S14',title:t=>`${t.short}: which parts of the skeleton are known`,role:'anatomy-plate',kind:'context-schematic',cls:'B',wave:3,fmt:'vector',
    brief:t=>`Skeleton-inventory diagram: a base skeleton template with the preserved elements highlighted, element list taken from the specimen record(s): ${[t.basis.primary,...t.basis.also].join('; ')}.`},
]

type Extra={taxonId:string;n:number;title:string;role:string;kind:MediaKindName;cls:EvidenceClass;fmt:keyof typeof FORMAT;brief:string;specimen?:string}
const EXTRAS:Extra[]=[
  {taxonId:'sahelanthropus',n:1,title:'Foramen magnum position: Toumaï vs chimpanzee vs modern human (basal views)',role:'anatomy-plate',kind:'context-schematic',cls:'B',fmt:'vector',brief:'Vector diagram from licensed basal-view scans; state that the evidence for upright posture is disputed.'},
  {taxonId:'orrin',n:1,title:'Femoral neck comparison: Orrorin, chimpanzee, Australopithecus, modern human',role:'anatomy-plate',kind:'context-schematic',cls:'B',fmt:'vector',brief:'Vector diagram from licensed femur images or published measurements; mark the interpretation as disputed.'},
  {taxonId:'ardipithecus',n:1,title:'Foot diagram: grasping big toe vs non-grasping foot',role:'anatomy-plate',kind:'context-schematic',cls:'B',fmt:'vector',brief:'Vector diagram from licensed foot images or published figures re-drawn with permission.'},
  {taxonId:'anamensis',n:1,title:'Proximal tibia and knee joint diagram',role:'anatomy-plate',kind:'context-schematic',cls:'B',fmt:'vector',brief:'Vector diagram from licensed tibia scans; label the joint-surface features linked to upright walking.'},
  {taxonId:'afarensis',n:1,title:'Laetoli footprint trail with scale',role:'context',kind:'specimen-photo',cls:'C',fmt:'plate',brief:`Photograph or cast of the Laetoli G-trail with a scale bar. ${SOURCE_ORDER}`},
  {taxonId:'afarensis',n:2,title:'Dikika child (DIK-1-1)',role:'specimen-reference',kind:'specimen-photo',cls:'C',fmt:'plate',specimen:'DIK-1-1',brief:`Photograph of the cranium and skeleton elements. ${PLATE_RULES} ${SOURCE_ORDER}`},
  {taxonId:'africanus',n:1,title:'Taung child skull with endocast',role:'specimen-reference',kind:'specimen-photo',cls:'C',fmt:'plate',specimen:'Taung 1',brief:`Photograph of the Taung child skull. ${PLATE_RULES} ${SOURCE_ORDER}`},
  {taxonId:'africanus',n:2,title:'Taung child: eagle-damage diagram',role:'anatomy-plate',kind:'context-schematic',cls:'B',fmt:'vector',brief:'Vector diagram of the orbit and skull damage pattern attributed to a large bird of prey; draw only what the publication documents.'},
  {taxonId:'habilis',n:1,title:'OH 24 (“Twiggy”) cranium',role:'specimen-reference',kind:'specimen-photo',cls:'C',fmt:'plate',specimen:'OH 24',brief:`Photograph of OH 24 (distorted cranium; note the distortion in the caption). ${PLATE_RULES} ${SOURCE_ORDER}`},
  {taxonId:'erectus',n:1,title:'Dmanisi crania series showing variation',role:'comparative-morphology',kind:'specimen-photo',cls:'C',fmt:'plate',specimen:'D2282, D2700, D4500',brief:`Aligned lateral views of the Dmanisi crania at one scale. ${PLATE_RULES} ${SOURCE_ORDER}`},
  {taxonId:'heidelbergensis',n:1,title:'Schöningen wooden spears',role:'behavior',kind:'specimen-photo',cls:'C',fmt:'plate',brief:`Photograph of the Schöningen spears. Hominin attribution to H. heidelbergensis is debated; say so in the caption. ${SOURCE_ORDER}`},
  {taxonId:'neanderthal',n:1,title:'Interpreted burial: excavation record (contested)',role:'context',kind:'specimen-photo',cls:'C',fmt:'plate',brief:`Excavation photograph or plan of an interpreted burial (for example Kebara 2 or Shanidar). The caption must say the burial interpretation is contested where it is. ${SOURCE_ORDER}`},
  {taxonId:'neanderthal',n:2,title:'Kebara 2 hyoid',role:'specimen-reference',kind:'specimen-photo',cls:'C',fmt:'plate',specimen:'Kebara 2',brief:`Photograph of the Kebara 2 hyoid with a scale bar. ${SOURCE_ORDER}`},
  {taxonId:'neanderthal',n:3,title:'Neanderthal, Denisovan and sapiens admixture diagram',role:'context',kind:'context-schematic',cls:'A',fmt:'vector',brief:'Generated by script from sourced admixture estimates; show ranges and the study each number comes from; no invented percentages.'},
  {taxonId:'sapiens',n:1,title:'Jebel Irhoud 1: facial reconstruction',role:'profile-portrait',kind:'reconstruction',cls:'D',fmt:'portrait',specimen:'Jebel Irhoud 1',brief:'Reconstruction of the early (about 315,000-year-old) face with a long, low braincase. Prompt provided.'},
  {taxonId:'sapiens',n:2,title:'Blombos engraved ochre',role:'behavior',kind:'specimen-photo',cls:'C',fmt:'plate',brief:`Photograph of an engraved ochre piece from Blombos Cave. ${SOURCE_ORDER}`},
  {taxonId:'sapiens',n:3,title:'Perforated shell beads',role:'behavior',kind:'specimen-photo',cls:'C',fmt:'plate',brief:`Photograph of perforated marine shell beads (for example from Skhul, Qafzeh or Blombos). ${SOURCE_ORDER}`},
  {taxonId:'sapiens',n:4,title:'Cave art',role:'behavior',kind:'specimen-photo',cls:'C',fmt:'plate',brief:`Photograph of dated cave art. ${SOURCE_ORDER}`},
]

const COMPARATIVE:{n:number;title:string;cls:EvidenceClass;kind:MediaKindName;brief:string}[]=[
  {n:1,title:'Skull lineup, lateral view, 11 taxa at one scale',cls:'B',kind:'context-schematic',brief:'Aligned renders from licensed scans (S04 sources), identical camera and scale.'},
  {n:2,title:'Skull lineup, frontal view, 11 taxa at one scale',cls:'B',kind:'context-schematic',brief:'As C01, frontal view.'},
  {n:3,title:'Cranial capacity ranges',cls:'A',kind:'context-schematic',brief:'Chart generated from a sourced table (taxon, min, max, specimen count, source id).'},
  {n:4,title:'Body height and mass bands',cls:'A',kind:'context-schematic',brief:'Chart generated from sourced ranges; bands, not points.'},
  {n:5,title:'Dental arcade and tooth-size comparison',cls:'B',kind:'context-schematic',brief:'Occlusal outlines traced from licensed scans at one scale.'},
  {n:6,title:'Pelvis comparison (ape, A. afarensis, H. sapiens)',cls:'B',kind:'context-schematic',brief:'Outlines traced from licensed images; labels from claims.'},
  {n:7,title:'Foot comparison',cls:'B',kind:'context-schematic',brief:'Outlines traced from licensed images; mark disputed interpretations.'},
  {n:8,title:'Hand comparison',cls:'B',kind:'context-schematic',brief:'Outlines traced from licensed images.'},
  {n:9,title:'Locomotion diagram',cls:'B',kind:'context-schematic',brief:'Schematic of quadrupedal, climbing and upright locomotion; clearly schematic, not a reconstruction.'},
  {n:10,title:'Endocast and brain-size comparison',cls:'B',kind:'context-schematic',brief:'Endocast renders from licensed scans at one scale.'},
  {n:11,title:'Stone-tool technology timeline',cls:'C',kind:'specimen-photo',brief:'Licensed photographs of dated Oldowan, Acheulean, Mousterian and Upper Palaeolithic examples arranged on a timeline.'},
  {n:12,title:'Facial profile comparison',cls:'B',kind:'context-schematic',brief:'Profile outlines traced from S04 images.'},
  {n:13,title:'Time ranges of the 11 taxa with uncertainty',cls:'A',kind:'context-schematic',brief:'Chart generated from the taxon records; uncertainty shown qualitatively.'},
  {n:14,title:'Key sites in Africa (early taxa)',cls:'A',kind:'context-schematic',brief:'Generated from the site records on the paleo layer; no routes implied.'},
  {n:15,title:'Key sites in Eurasia (later taxa)',cls:'A',kind:'context-schematic',brief:'Generated from the site records on the paleo layer; no routes implied.'},
  {n:16,title:'Admixture and dispersal summary',cls:'A',kind:'context-schematic',brief:'Generated from sourced records only; see the Migration plan (phase P6).'},
  {n:17,title:'Stone-tool industries timeline with taxon associations',cls:'A',kind:'context-schematic',brief:'Chart generated from a sourced table (industry, start, end, regions, associated taxa, attribution certainty): Lomekwian, Oldowan, Acheulean, Mode 3 (Middle Stone Age / Mousterian), Mode 4. Attribution drawn as “associated” or “unattributed”, never as “made by”.'},
  {n:18,title:'Technological modes 1–5: schematic',cls:'B',kind:'context-schematic',brief:'Vector schematic of the five technological modes (Mode 1 core and flake, Mode 2 bifaces, Mode 3 prepared cores, Mode 4 blades, Mode 5 microliths), drawn from licensed artefact images or published drawings used with permission.'},
  {n:19,title:'How a flake is made: conchoidal fracture',cls:'B',kind:'context-schematic',brief:'Vector explanatory diagram of direct percussion: hammerstone, striking platform, bulb of percussion, ripples, flake scars and cortex. Mechanism only; no site or species claim.'},
  {n:20,title:'Earliest stone-tool evidence, unattributed: Lomekwi 3 and Dikika cut marks',cls:'C',kind:'specimen-photo',brief:`Licensed photographs of Lomekwi 3 artefacts and of the Dikika cut-marked bones, captioned as unattributed to a species and (for Dikika) disputed. ${SOURCE_ORDER}`},
  {n:21,title:'Real artefacts at one scale: Oldowan, Acheulean, Mousterian and Still Bay',cls:'C',kind:'specimen-photo',brief:`Licensed photographs of a dated chopper, handaxe, Mousterian point and Still Bay point on one scale bar. ${SOURCE_ORDER}`},
]

const pad=(n:number)=>String(n).padStart(2,'0')
const fmtOf=(key:keyof typeof FORMAT)=>FORMAT[key]
const PROMPT_FILE=(taxonId:string)=>`prompts/${taxonId}.md`

function statusFor(taxon:TaxonBrief,series:string):{status:RowStatus;reason:string}{
  if(series.startsWith('L')&&!taxon.lithics) return {status:'NOT-APPLICABLE',reason:taxon.noLithicsReason}
  if(series==='S11'&&!taxon.behavior) return {status:'NOT-APPLICABLE',reason:'No source-supported behaviour for this taxon; revisit only when evidence is registered.'}
  if(taxon.basis.catalogIds.length===0) return {status:'BLOCKED-NO-SPECIMEN',reason:'No specimen record exists in content/specimens.ts yet; no image may be made before it exists.'}
  return {status:'TODO',reason:''}
}

export function buildCatalog():CatalogRow[]{
  const rows:CatalogRow[]=[]
  for(const taxon of TAXA){
    const specimenRef=[taxon.basis.primary,...taxon.basis.also].join(' | ')
    for(const series of SERIES){
      const format=fmtOf(series.fmt)
      const {status,reason}=statusFor(taxon,series.code)
      rows.push({code:`${taxon.id}.${series.code}`,taxonId:taxon.id,series:series.code,title:series.title(taxon),role:series.role,mediaKind:series.kind,evidenceClass:series.cls,wave:series.wave,ratio:format.ratio,size:format.size,status,statusReason:reason,specimenRef,brief:series.brief(taxon),promptFile:series.cls==='D'&&status!=='NOT-APPLICABLE'?PROMPT_FILE(taxon.id):''})
    }
    for(const extra of EXTRAS.filter(item=>item.taxonId===taxon.id)){
      const format=fmtOf(extra.fmt)
      const {status,reason}=statusFor(taxon,'X')
      rows.push({code:`${taxon.id}.X${extra.n}`,taxonId:taxon.id,series:`X${extra.n}`,title:`${taxon.short}: ${extra.title}`,role:extra.role,mediaKind:extra.kind,evidenceClass:extra.cls,wave:4,ratio:format.ratio,size:format.size,status,statusReason:reason,specimenRef:extra.specimen??specimenRef,brief:extra.brief,promptFile:extra.cls==='D'?PROMPT_FILE(taxon.id):''})
    }
  }
  for(const taxon of TAXA){
    const l=taxon.lithics
    const kind:MediaKindName='specimen-photo'
    const specimenRef=l?`${l.industry} — type sites: ${l.typeSites.join('; ')}`:''
    const specs:{n:number;title:string;cls:EvidenceClass;mk:MediaKindName;role:string;fmt:keyof typeof FORMAT;brief:string}[]=[
      {n:1,title:`${taxon.short}: stone-tool kit (flat lay with scale)`,cls:'C',mk:kind,role:'behavior',fmt:'plate',
        brief:l?`Licensed photograph of dated artefacts from the ${l.industry}: ${l.kit.join('; ')}. Flat lay on a neutral background with a scale bar; each artefact with site, layer and age. Search terms: ${l.searchTerms.join(' | ')}. Attribution caution: ${l.attribution} ${SOURCE_ORDER}`:''},
      {n:2,title:`${taxon.short}: key tool type — ${l?l.keyType:'none'}`,cls:'C',mk:kind,role:'specimen-reference',fmt:'plate',
        brief:l?`Licensed photograph of one dated artefact (${l.keyType}), both faces, with a scale bar. Type sites: ${l.typeSites.join('; ')}. ${l.caution} ${SOURCE_ORDER}`:''},
      {n:3,title:`${taxon.short}: how the tools were made`,cls:'B',mk:'context-schematic',role:'anatomy-plate',fmt:'vector',
        brief:l?`Vector diagram of the reduction sequence: ${l.sequence}. Drawn from licensed artefact images or experimental-replication photographs; labels from claim records. ${l.caution}`:''},
    ]
    for(const spec of specs){
      const format=fmtOf(spec.fmt)
      const {status,reason}=statusFor(taxon,`L${spec.n}`)
      rows.push({code:`${taxon.id}.L${spec.n}`,taxonId:taxon.id,series:`L${spec.n}`,title:spec.title,role:spec.role,mediaKind:spec.mk,evidenceClass:spec.cls,wave:6,ratio:format.ratio,size:format.size,status,statusReason:reason,specimenRef,brief:status==='NOT-APPLICABLE'?`Not applicable: ${reason}`:spec.brief,promptFile:''})
    }
  }
  for(const item of COMPARATIVE){
    const format=item.cls==='A'||item.cls==='B'?FORMAT.vector:FORMAT.plate
    rows.push({code:`compare.C${pad(item.n)}`,taxonId:null,series:`C${pad(item.n)}`,title:item.title,role:'comparative-morphology',mediaKind:item.kind,evidenceClass:item.cls,wave:5,ratio:format.ratio,size:format.size,status:'TODO',statusReason:'',specimenRef:'',brief:item.brief,promptFile:''})
  }
  return rows
}

/* ---------------------------------------------------------------- prompts (class D) */

const CONVENTIONS=[
  'EVIDENCE TIERS. BONE-ANCHORED = directly constrained by the fossils: render with confidence. INFERRED = reasoned from related species and ecology: render plausibly but unobtrusively. CONVENTION = not knowable: use the convention stated for this taxon and add no striking detail.',
  'SOFT TISSUE: follow standard forensic facial-approximation soft-tissue depths at craniometric landmarks; no exaggeration of muscle, fat, lips or nose beyond what the skeleton supports.',
  'EYES: dark brown irises. For non-Homo hominins keep the sclera (eye white) pigmented rather than bright white; for Homo a light sclera is acceptable. This is a convention, not a finding.',
  'EXPRESSION: neutral and calm. Not aggressive, not smiling, no ape-like grimace, no “caveman” trope.',
  'NO RACIAL CARICATURE: do not mimic any living ethnic group; keep pigmentation and hair exactly as the convention says.',
  'NON-SEXUALISED (strict): no visible genitals and no full-frontal nudity in any image. Non-Homo hominins: dense short body hair covering torso and hips, plus posture and distance. Homo: the waist wrap stated in the clothing convention, plus posture; never a bare, hairless full-frontal body.',
]

const MUST_NOT=[
  'any text, caption, label, signature, watermark, logo, border or frame',
  'modern objects: clothing, jewellery, metal, woven textiles, ceramics, glasses, tattoos, modern haircuts or beard styling',
  'domesticated animals or crops',
  'fire, weapons or tools unless this brief explicitly lists them',
  'monstrous, brutish or “ape-man” stylisation; glowing eyes; dramatic cinematic lens flares',
  'more individuals than specified; any hominin in a habitat-only image',
  'visible genitals, full-frontal nudity, or hairless bare bodies',
]

const SELF_CHECK=(extra:string)=>`Before you output the final image, silently verify: (1) aspect ratio is exactly as specified; (2) every BONE-ANCHORED feature listed is visible and correct; (3) nothing from MUST NOT appears; (4) there is no text anywhere in the image; (5) skin, hair and clothing follow the stated convention; ${extra}. If any check fails, regenerate.`

const AFTER=`After the image, add an ASSUMPTIONS list of at most 120 words stating which features you rendered as BONE-ANCHORED, INFERRED and CONVENTION. Do not claim anything you did not do.`

const bullets=(items:string[])=>items.map(item=>`- ${item}`).join('\n')

const reference=(t:TaxonBrief)=>
`REFERENCE INPUT (optional; attach if the tool accepts images): (a) a lateral-view photograph or render of ${t.basis.primary}; (b) a frontal-view photograph or render of the same specimen; (c) a modern human skull in the same view and at the same scale, for proportion only. If nothing is attached, follow the written morphology literally and say so in the assumptions list.`

const header=(code:string,title:string,t:TaxonBrief,cls:string,ratio:string,size:string)=>
`### ${code} — ${title}
Evidence class ${cls} (reconstruction) · ${ratio} · ${size} · basis: ${t.basis.primary}
Copy everything inside the box below into the image tool.`

const box=(text:string)=>'```text\n'+text.trim()+'\n```'

function portrait(t:TaxonBrief):string{
  if(t.noCranium){
    return `${header(`${t.id}.S02`,`${t.short}: portrait (bone-inventory silhouette)`,t,'D',FORMAT.portrait.ratio,FORMAT.portrait.size)}

${box(`Create ONE scientific illustration for a science-education atlas of human evolution (Human Origins): a bone-inventory silhouette of ${t.name}.
OUTPUT: single image, portrait 4:5, 1000×1250 px, plain neutral dark-grey background.
WHY THIS FORMAT: no cranium of ${t.short} is known (${t.basis.primary}). A face MUST NOT be invented.
TASK: draw a flat, softly shaded full-body outline of a small, chimpanzee-sized bipedal-capable hominin in profile, as a uniform mid-grey silhouette with NO face, NO eyes, NO nose, NO mouth, NO hair texture and NO skin detail. Inside the silhouette render, as realistic ivory-coloured bones, ONLY the elements that exist: ${t.keyBones.join('; ')}; leave the rest of the silhouette empty.
BONE-ANCHORED FEATURES:
${bullets(t.bone)}
DO NOT INVENT:
${bullets(t.unknown)}
STYLE: restrained scientific-plate style, soft top-left light, muted palette, generous empty margin.
${bullets(['MUST NOT include: '+MUST_NOT.join('; ')]).slice(2)}
${SELF_CHECK('(6) the head is a blank, featureless shape; (7) only the listed bones are drawn')}
${AFTER}`)}`
  }
  return `${header(`${t.id}.S02`,`${t.short}: portrait`,t,'D',FORMAT.portrait.ratio,FORMAT.portrait.size)}

${box(`Create ONE scientific paleoart portrait of ${t.name} for a science-education atlas of human evolution (Human Origins). It must be an evidence-based facial reconstruction, not entertainment art.
OUTPUT: single image, portrait 4:5, 1000×1250 px, head and shoulders, three-quarter view, neutral mid-grey seamless background, even soft studio-style light.
SUBJECT: ${t.individual}. Lived ${t.ageText}; region: ${t.region}.
BASIS: ${t.basis.primary}${t.basis.also.length?`; also consulted: ${t.basis.also.join('; ')}`:''}.
${reference(t)}
BONE-ANCHORED FEATURES (render with confidence):
${bullets(t.bone)}
SIZE REFERENCE: braincase ${t.brain}. BODY: ${t.body}.
DO NOT INVENT (leave unremarkable and do not add striking detail):
${bullets(t.unknown)}
CONVENTIONS FOR THIS TAXON (not findings): skin and hair — ${t.skinHair}. Clothing — ${t.clothing}.
${bullets(CONVENTIONS)}
STYLE: photorealistic, restrained documentary-style paleoart; natural skin texture; muted palette; no dramatic lighting.
MUST NOT include: ${MUST_NOT.join('; ')}.
${SELF_CHECK('(6) exactly one individual is shown')}
${AFTER}`)}`
}

function hero(t:TaxonBrief):string{
  const empty=!!t.noCranium
  const scene=empty
    ?`Create ONE wide landscape image of the paleoenvironment of ${t.name}: ${t.heroScene}.`
    :`Create ONE wide scientific paleoart scene for ${t.name}.`
  return `${header(`${t.id}.S03`,`${t.short}: dossier hero`,t,'D',FORMAT.hero.ratio,FORMAT.hero.size)}

${box(`${scene} This image is for a science-education atlas of human evolution (Human Origins); it must be evidence-based, not entertainment art.
OUTPUT: single image, 16:9, 1920×1080 px, wide landscape composition, horizon in the upper third, natural daylight.
TIME AND PLACE: ${t.ageText}; ${t.region}.
SCENE: ${t.heroScene}.
${empty?'NO hominin figure appears in this image.':`Individuals are small in the frame (each under one third of the image height) so the environment dominates. Show exactly the individuals described in SCENE, no more.
REFERENCE INPUT (optional): the previously generated portrait of this species, if you have one, for head and body proportions. Otherwise follow the morphology below literally.
BONE-ANCHORED FEATURES OF THE INDIVIDUALS:
${bullets(t.bone)}
BODY: ${t.body}.
CONVENTIONS (not findings): skin and hair — ${t.skinHair}. Clothing — ${t.clothing}.`}
ENVIRONMENT: ${t.habitat.setting}. Vegetation: ${t.habitat.flora}. Animals (kinds only; do not add modern iconic species): ${t.habitat.fauna.replace(/^kinds only:\s*/,'')}. Climate and season: ${t.habitat.climate}.
BEHAVIOUR: only calm everyday activity (foraging, resting, walking, drinking). No hunting, no violence, no ritual, no tools or fire unless listed in SCENE.
${bullets(CONVENTIONS)}
STYLE: photorealistic, restrained documentary-style paleoart; muted natural palette; no lens flares.
MUST NOT include: ${MUST_NOT.slice(0,5).join('; ')}.
${SELF_CHECK(empty?'(6) there is no hominin figure':'(6) the number and relative size of individuals match SCENE')}
${AFTER}`)}`
}

function habitat(t:TaxonBrief):string{
  return `${header(`${t.id}.S10`,`${t.short}: habitat`,t,'D',FORMAT.hero.ratio,FORMAT.hero.size)}

${box(`Create ONE landscape image of the paleoenvironment where ${t.name} lived. This image is for a science-education atlas of human evolution (Human Origins); it must be evidence-based, not entertainment art.
OUTPUT: single image, 16:9, 1920×1080 px, natural daylight, wide landscape.
TIME AND PLACE: ${t.ageText}; ${t.region}.
SETTING: ${t.habitat.setting}.
VEGETATION: ${t.habitat.flora}. Depict plant KINDS and growth forms appropriate to the period; do not add crops, ornamental or modern invasive plants.
ANIMALS (kinds only, small in the frame; do not add modern iconic species): ${t.habitat.fauna.replace(/^kinds only:\s*/,'')}.
CLIMATE AND SEASON: ${t.habitat.climate}.
NO hominin figures, NO tools, NO fire, NO footprints and NO structures appear in this image. It is a habitat-only plate.
STYLE: photorealistic, restrained documentary-style landscape; muted natural palette; no lens flares, no glowing sky.
MUST NOT include: ${MUST_NOT.filter((_,i)=>i!==5).join('; ')}; any hominin.
${SELF_CHECK('(6) no hominin appears')}
${AFTER}`)}`
}

function behavior(t:TaxonBrief):string{
  const b=t.behavior!
  return `${header(`${t.id}.S11`,`${t.short}: ${b.title}`,t,'D',FORMAT.plate.ratio,FORMAT.plate.size)}

${box(`Create ONE scientific paleoart scene: ${b.title}, for ${t.name}. This image is for a science-education atlas of human evolution (Human Origins); it must be evidence-based, not entertainment art.
OUTPUT: single image, 4:3, 1600×1200 px, natural daylight, medium-wide shot, subjects occupy about half of the frame height.
EVIDENCE THIS SCENE RESTS ON: ${b.evidence}.
SCENE: ${b.scene}.
OBJECTS AND TOOLS (exactly these, drawn accurately for the period): ${b.objects}.
CAUTION: ${b.caution}.
REFERENCE INPUT (optional): the previously generated portrait of this species, if you have one, for head and body proportions, and a photograph of the real artefact type listed below. Otherwise follow the morphology below literally.
BONE-ANCHORED FEATURES OF THE INDIVIDUALS:
${bullets(t.bone)}
BODY: ${t.body}.
CONVENTIONS (not findings): skin and hair — ${t.skinHair}. Clothing — ${t.clothing}.
ENVIRONMENT: ${t.habitat.setting}; vegetation: ${t.habitat.flora}; climate: ${t.habitat.climate}.
${bullets(CONVENTIONS)}
STYLE: photorealistic, restrained documentary-style paleoart; muted natural palette; no gore; no lens flares.
MUST NOT include: ${MUST_NOT.slice(0,3).join('; ')}; weapons or tools not listed above; animals being killed.
${SELF_CHECK('(6) only the listed objects and tools appear, drawn in period-appropriate form')}
${AFTER}`)}`
}

function irhoud(t:TaxonBrief):string{
  return `${header('sapiens.X1','H. sapiens: Jebel Irhoud 1, facial reconstruction',t,'D',FORMAT.portrait.ratio,FORMAT.portrait.size)}

${box(`Create ONE scientific paleoart portrait of an early Homo sapiens based on Jebel Irhoud 1 (Morocco, about 315,000 years ago) for a science-education atlas of human evolution (Human Origins). Evidence-based facial reconstruction, not entertainment art.
OUTPUT: single image, portrait 4:5, 1000×1250 px, head and shoulders, three-quarter view, neutral mid-grey seamless background, even soft light.
SUBJECT: one adult; sex not asserted by the specimen — draw an adult male as a visual convention (verify in the specimen record).
REFERENCE INPUT (attach if the tool accepts images; otherwise follow the written morphology literally and say so): lateral and frontal views of Jebel Irhoud 1, and a modern human skull in the same view for proportion only.
BONE-ANCHORED FEATURES (render with confidence; verify against the publications):
- a face that is short, flat and tucked beneath the braincase, similar to modern humans
- a long, low braincase that is NOT globular, with a receding forehead (unlike later modern humans)
- a moderate, continuous brow ridge more pronounced than in recent humans
- large teeth relative to recent humans
- braincase size about 1,300–1,400 cc (verify)
DO NOT INVENT: nose and lip soft tissue; skin, hair and eye colour; facial hair; ornament.
CONVENTIONS (not findings): medium to dark brown skin; dark, straight-to-wavy hair, loose or simply tied; no clothing visible at head-and-shoulders framing.
${bullets(CONVENTIONS)}
STYLE: photorealistic, restrained documentary-style paleoart; natural skin texture; muted palette.
MUST NOT include: ${MUST_NOT.join('; ')}.
${SELF_CHECK('(6) exactly one individual is shown; (7) the braincase is long and low, not globular')}
${AFTER}`)}`
}

/** Editorial “verify” notes are for humans (see taxa.ts); they must not reach the image tool. */
const scrub=(text:string)=>text
  .replace(/\s*\((?:kinds only;\s*)?verify[^)]*\)/g,'')
  .replace(/;\s*verify[^)]*\)/g,')')
  .replace(/,\s*verify[^)]*\)/g,')')

export function composePromptFiles():Record<string,string>{
  const files:Record<string,string>={}
  for(const t of TAXA){
    const parts:string[]=[`# ${t.name} — image prompts (class D)

Generated by \`npm run images:build\` from \`tools/images/taxa.ts\` and \`tools/images/spec.ts\`. **Do not edit this file by hand.** Read \`_global.md\` first. Each prompt below is self-contained.
`]
    parts.push(portrait(t),hero(t),habitat(t))
    if(t.behavior) parts.push(behavior(t))
    if(t.id==='sapiens') parts.push(irhoud(t))
    files[PROMPT_FILE(t.id)]=scrub(parts.join('\n\n')+'\n')
  }
  files['prompts/_global.md']=GLOBAL_DOC
  files['prompts/ALL.md']=composeAll(files)
  return files
}

/** One clean file: heading + copy-ready box per prompt, in path order, nothing else. */
function composeAll(files:Record<string,string>):string{
  const blocked=new Set(buildCatalog().filter(row=>row.status==='BLOCKED-NO-SPECIMEN').map(row=>row.code))
  const out:string[]=['# Human Origins — image prompts (all, in order)\n']
  for(const t of TAXA){
    out.push(`## ${t.name}\n`)
    const sections=files[PROMPT_FILE(t.id)].split('\n### ').slice(1)
    for(const section of sections){
      const heading=section.split('\n')[0]
      const code=heading.split(' — ')[0]
      const box=/```text\n[\s\S]*?\n```/.exec(section)![0]
      out.push(`### ${heading}${blocked.has(code)?' [on hold: specimen record not yet registered]':''}\n\n${box}\n`)
    }
  }
  return out.join('\n')
}

const GLOBAL_DOC=`# Image prompts — read me first

**Purpose.** Self-contained prompts for the class-D images of the Human Origins atlas (portraits, hero scenes, habitats, documented-behaviour scenes). They work in ChatGPT (image generation) or any generator that accepts a long text prompt, and they double as a brief for an artist or 3D modeller.

**What AI may and may not make.**
- Class D only (reconstructions). Never class C (photographs of real specimens, sites, artefacts): a generated image of a fossil would be fabricated evidence.
- Every output is a **draft** until a reviewer signs the checklist below. Publish only with \`evidenceClass: reconstruction\`, a visible “reconstruction” label, the assumptions list and the reviewer.

**How to use a prompt (ChatGPT or similar).**
1. Open a new conversation for each image (so earlier images do not leak into it).
2. Attach the reference images named in REFERENCE INPUT (rendered or photographed from licensed scans; see classes B and C in the catalog). If you cannot attach them, say so; the prompt still works from the written morphology, but expect lower accuracy.
3. Paste everything inside the box. Ask for **one** image.
4. If the result breaks a rule, reply with the specific failed check and ask for a regeneration. Do not accept “close enough” on a BONE-ANCHORED feature.
5. Save the image and fill the assumptions sheet (below). Upload through the CMS (admin → Media) only after review.

**Project conventions (apply to every prompt).**
- Skin, hair and eye colour are not preserved in fossils. The conventions in each prompt are stated as conventions, never as findings.
- Neutral expression, non-sexualised framing, no racial caricature, no text or watermark in the image.
- Fauna are given as *kinds*; the species must be verified against the site faunal list before publication.

**Assumptions sheet (fill for every published image).**
\`\`\`text
image code:
generator and version:
date:
prompt file and prompt id:
reference images used (code, licence):
bone-anchored features confirmed visible (list):
conventions applied (list):
deviations from the brief and how they were handled:
regenerated N times, reason:
reviewer, date, decision (approve / revise / reject):
\`\`\`

**Reviewer checklist.**
1. Every BONE-ANCHORED feature is visible and correct against the reference scans.
2. Nothing under DO NOT INVENT has been rendered as a striking, specific detail.
3. No anachronism (objects, tools, fire, clothing) beyond what the brief lists.
4. Skin, hair, eye colour follow the stated convention; no stereotype.
5. Fauna kinds match the verified site faunal list.
6. The caption says “reconstruction”, names the specimen basis and lists the main uncertainties.
7. Licence and credit fields are complete (the generator’s terms allow this use).
`
